version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all-actions:
        patterns: [ "*" ]
    assignees:
      - infrastructure
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    security-updates-only: true
    assignees:
      - infrastructure
  - package-ecosystem: "docker"
    directories:
      - "/scripts/ci/images"
      - "/scripts/ci/images/spack"
      - "/scripts/ci/images/formatting"
    schedule:
      interval: "weekly"
    security-updates-only: true
    assignees:
      - infrastructure
  - package-ecosystem: "conda"
    directory: "/docs/"
    schedule:
      interval: "weekly"
    security-updates-only: true
    assignees:
      - infrastructure

