version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all-actions:
        patterns: [ "*" ]
    assignees:
      - infrastructure
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - infrastructure
  - package-ecosystem: "docker"
    directories:
      - "/scripts/ci/images"
      - "/scripts/ci/images/spack"
      - "/scripts/ci/images/formatting"
    schedule:
      interval: "weekly"
    assignees:
      - infrastructure
