name: adios2-python-docs

channels:
  - conda-forge

dependencies:
  - breathe
  - cmake
  - docutils
  - libpython-static
  - ninja
  - numpy
  - pip
  - python ==3.12
  - setuptools <81      # last version with pkg_resources
  - sphinx
  - pip:
    - sphinxcontrib-mermaid
    - sphinx_rtd_theme
